### ISSUE TITLE
Count of censored words

### ISSUE THREAD

**Issue by EvanBurbidge** [kaikalii/censor#4]
**Feature request**

Hi,

Love using this create first of all, I'm wondering would it be possible to add a count method to the create

at the moment i'm censoring words and then counting the instances of the replacements in my string

Would be nice to have a censor.count("str") method available 

I'm assuming you loop the string to find censorable words so would it be possible to store a count on the string?

thanks! :)

**Comment by kaikalii** [comment]
666709779e5961a91903c823b6929249073644ba closes this.
See also [#5 ](https://github.com/kaikalii/censor/pull/5#issuecomment-1317394710)
